### ISSUE TITLE
HOMEPAGE - SIDE NAV - Add the icons for the tools, and make the txt size on those two lines 32pt

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#10]

**Comment by tbrodahl** [comment]
![navicons](https://cloud.githubusercontent.com/assets/5798011/20071653/289bbace-a4da-11e6-9170-25d08978227a.jpg)

**Comment by andrewmartin** [comment]
Can you please try to add these to the Sketch file for me? Use the `symlink` folder and just follow the patterns I did for the other icons. I was having some issues getting those out. Let me know if you have any questions, I don't think it should take long. Once you save the file, I'll load in.

**Comment by tbrodahl** [comment]
![image](https://cloud.githubusercontent.com/assets/5798011/20074217/33545f8e-a4e4-11e6-8428-bb954d8b5bb5.png)

Scaling these won't work, and flattening won't work either because they are lines and not shapes. Recreating them with shapes would take hours.

Those Icons only show up in that one place and don't need to be in the font. Especially since we won't be changing their colors.

**Comment by andrewmartin** [comment]
Retina PNG it is for these, I assume they’re already in the Dropbox.
