### ISSUE TITLE
HOMEPAGE - People Matrix - Mouse over shifts the images slightly - should be exactly same

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#11]

**Comment by tbrodahl** [comment]
![image](https://cloud.githubusercontent.com/assets/5798011/20071837/e8959f84-a4da-11e6-8261-2a1b35efc87d.png)

**Comment by tbrodahl** [comment]
Think this happens when i've resized the window? See if it happens to you?

**Comment by andrewmartin** [comment]
This one was giving me a lot of issues, there's some problems with 0.5px widths here. I really don't know how to fix this easily unless we set hardcoded heights on the divs, so i'll try that next.

**Comment by tbrodahl** [comment]
K. Not a huge issue, but would be great if we could find a fix.
