### ISSUE TITLE
HOMEPAGE - Can we scale the logo and txt up top progressively, so its not huge on the mid screen sizes

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#12]

**Comment by tbrodahl** [comment]
![screen shot 2016-11-07 at 11 06 34 am](https://cloud.githubusercontent.com/assets/5798011/20071703/518b89a0-a4da-11e6-94bc-c5572fd0ac0e.png)

**Comment by andrewmartin** [comment]
We can, but I wasn't able to pull a working SVG for this item.

**Comment by tbrodahl** [comment]
I tried exporting it as SVG but something seems off? Maybe have a look?

**Comment by andrewmartin** [comment]
Where did you export it to?

**Comment by tbrodahl** [comment]
To the IMGs folder

**Comment by andrewmartin** [comment]
My bad, must’ve not finished syncing. I’ll take a look, thanks! This one would really help to at least get as an SVG, especially if you want to control the scaling. Keep in mind, if we do scale it, at certain window widths (odd numbers) it will probably still look blurry. Is that OK?

**Comment by andrewmartin** [comment]
So, the SVG didn't work, unfortunately (using the inline svg method, not font kit). 

I'm not sure how to quickly build out a responsive image without knowing exactly what percentages to work with. Not sure how to proceed on this one, but considering we have a lot to do, hoping we can table this.
