### ISSUE TITLE
menu button not accessible in safari

### ISSUE THREAD

**Issue by andrewmartin** [tbrodahl/truenth#14]
the menu button doesn't work and offers a strange cursor in safari

![image](https://cloud.githubusercontent.com/assets/273842/20155426/ac6f39c8-a680-11e6-9cb1-89a27be5f10a.png)

**Comment by andrewmartin** [comment]
I just tested this and it seems to work for me? Is this still an issue?

**Comment by tbrodahl** [comment]
I still get taht icon on Safari when i use the side nav

**Comment by andrewmartin** [comment]
If you're talking about the icon that appears on the right side when the nav slides out, that's intentional. It's to indicate you can click to close the nav out?

![](http://cloud.believelabs.com/0E0n1e1G3k2R/Screen%20Recording%202016-11-18%20at%2018.28.gif)

**Comment by tbrodahl** [comment]
It shows up over the NAV items as well. Makes it seem like you can't click anything

**Comment by andrewmartin** [comment]
when the menu is open, you can't. click on anything though?

it's meant to indicate clicking will close the nav, does that make sense?

## 

Andrew Martin
Interactive Developer
believelabs.com
andrewmart.in
