### ISSUE TITLE
ABOUT - Current Projects - ADD two more TOOLS

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#19]
Tool No 3: All Stages 
EXERCISE AND DIET 
Personalized guides 
(Coming 2017)

and 

Tool No 6: Post Diagnosis 
Care Plan
Navigation resources 
(Coming Soon)

Make SEXUAL HEALTH #5

**Comment by andrewmartin** [comment]
Hm. I'm confused, there is no "SEXUAL HEALTH"...

**Comment by andrewmartin** [comment]
![](http://cloud.believelabs.com/1B3g1b1Q1v3l/Image%202016-11-18%20at%2016.45.33.png)
