### ISSUE TITLE
MOBILE - NAVBAR buttons should have the bg color even at the top of the page

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#22]
![screen shot 2016-11-18 at 4 27 19 pm](https://cloud.githubusercontent.com/assets/5798011/20451233/f7365e14-adab-11e6-8954-0f8f231c5635.png)
![screen shot 2016-11-18 at 4 28 01 pm](https://cloud.githubusercontent.com/assets/5798011/20451236/fc879a86-adab-11e6-951d-34504125083a.png)

**Comment by tbrodahl** [comment]
Still has white background on my end... buttons when they are on white should always have the BG colored BOX

**Comment by andrewmartin** [comment]
fixed
