### ISSUE TITLE
FOOTER - TrueNTH logo is not there 60% of the time

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#23]
Something strange going on with that file. maybe need to replace... has been happening for a while...

![screen shot 2016-11-18 at 4 34 24 pm](https://cloud.githubusercontent.com/assets/5798011/20451350/fdaa3b5c-adac-11e6-9e90-c007e14a3e4a.png)

**Comment by andrewmartin** [comment]
Hmm, I haven't missed it? This is happening on the S3 link right, not the `ngrok`?
