### ISSUE TITLE
CLEAN UP SIDE NAV

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#28]
![image](https://cloud.githubusercontent.com/assets/5798011/20452411/ea727bd8-adbd-11e6-980e-9e3c9fb56ff8.png)

lets differentiate the Join Us buttons

**Comment by andrewmartin** [comment]
What do you want me to do here?

**Comment by tbrodahl** [comment]
add LOG IN and SIGN UP as little boxes instead of text like the rest of the menu

**Comment by tbrodahl** [comment]
![image](https://cloud.githubusercontent.com/assets/5798011/20452643/b4658598-adc3-11e6-87ed-8366c929442f.png)

Thats what it is currently

**Comment by andrewmartin** [comment]
Sorry, missed your first screenshot, ok

**Comment by tbrodahl** [comment]
Can we give them a different MOUSE OVER color so the box doesn't disappear? 

#D2D1C5

**Comment by andrewmartin** [comment]
Done
