### ISSUE TITLE
MOBILE 500 - INFO BOXES CSS Change

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#30]
![image](https://cloud.githubusercontent.com/assets/5798011/20452474/5df51d3a-adbf-11e6-9759-4291588bb60a.png)

.mini-box__head {
font-size: 11px;
line-height: 16px;

change to

font-size: 14px;
line-height: 18px;

—

.mini-box__copy, .mini-box__list {
font-size: 13px;
line-height: 20px;

change to

font-size: 15px;
line-height: 20px;

**Comment by andrewmartin** [comment]
I'm not seeing either of these styles; cache refreshed?
