### ISSUE TITLE
MOBILE 500 NAV sizing needs CSS tweak

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#31]
![image](https://cloud.githubusercontent.com/assets/5798011/20452482/8864a126-adbf-11e6-8f4a-b0e4110d6dfa.png)

@media (max-width: 767px)
.side-nav-items__item {
font-size: 20px;
line-height: 24px;

change to

font-size: 28px;
line-height: 28px;

——

.side-nav-items__item--accentuated a {
font-size: 28px;
line-height: 32px;

change to

font-size: 25px;
line-height: 28px;

**Comment by andrewmartin** [comment]
this has been done?
