### ISSUE TITLE
MOBILE HOME TOP IMAGE can i give you a taller version for this size?

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#34]
![2016-11-18 19 03 18](https://cloud.githubusercontent.com/assets/5798011/20452584/425b4eb6-adc2-11e6-9cea-fdd6b5577946.png)

**Comment by andrewmartin** [comment]
We can try that. let me know when image is ready

## 

Andrew Martin
Interactive Developer
believelabs.com
andrewmart.in

**Comment by andrewmartin** [comment]
I adjusted some padding here and I think it's looking a little better, let me know?
