### ISSUE TITLE
MOBILE PROSTATE CANCER FACTS - Make the boxes stack instead of 2 columns

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#35]
Currently it breaks the width of the page. 
![2016-11-18 18 58 22](https://cloud.githubusercontent.com/assets/5798011/20452593/7a26d18a-adc2-11e6-8d39-cdb15ea3a942.png)
![2016-11-18 18 58 06](https://cloud.githubusercontent.com/assets/5798011/20452594/7c2b2594-adc2-11e6-81ea-285040b5301b.png)
![2016-11-18 18 57 54](https://cloud.githubusercontent.com/assets/5798011/20452595/7ea6b658-adc2-11e6-9b67-c9ae0400e09d.png)

**Comment by andrewmartin** [comment]
Got this one done. I fixed that wonky padding on the left and right, too.
