### ISSUE TITLE
ADMIN TOP BAR

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#39]
![image](https://cloud.githubusercontent.com/assets/5798011/20458474/42713552-ae5b-11e6-8598-f9f329d208b6.png)

Can we have that box with the arrow instead of the hamburger? Thx. 

And a separate blank page with the top bar so we can show them how this should look?

**Comment by tbrodahl** [comment]
On the left side of the bar is what i am referencing.

**Comment by andrewmartin** [comment]
`/index-admin.html` is available.
