### ISSUE TITLE
JOIN US pop up tweaks

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#41]
1) Can we make the box a little narrower - feels stretched wide right now

2) Take away the line that says IF YOURE A PATIENT

3) Can we make the CREATE ACCOUNT the same size as the MORE INFO buttons  (feels too small now)

![image](https://cloud.githubusercontent.com/assets/5798011/20458843/17be0cea-ae65-11e6-9788-1f185e4f4a94.png)

4) On mobile view, lets keep a little padding around the JOIN US box so it doesn't go full width. And the CREATE ACCOUNT button shouldn't get so wide either. 

![image](https://cloud.githubusercontent.com/assets/5798011/20458851/4ec8a10a-ae65-11e6-82ae-80b814ff9383.png)

**Comment by tbrodahl** [comment]
And can we make sure that SIGN UP stacks nicely on MOBILE?

![image](https://cloud.githubusercontent.com/assets/5798011/20458861/717f784a-ae65-11e6-825c-7e9de2395333.png)

**Comment by tbrodahl** [comment]
On MOBILE size, the X doesn't seem to work
![image](https://cloud.githubusercontent.com/assets/5798011/20458865/96df692e-ae65-11e6-80ec-a524adfca874.png)

**Comment by tbrodahl** [comment]
And can we make the BLUE OVERLAY in the BG be 90% opacity

**Comment by andrewmartin** [comment]
I hopefully got these done...
