### ISSUE TITLE
ARROWS ON START look smaller than before

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#46]
![image](https://cloud.githubusercontent.com/assets/5798011/20458978/ad562470-ae67-11e6-9e89-e4feea89b8b9.png)

**Comment by andrewmartin** [comment]
They're the same arrows we've had I believe, can you tweak the font size and let me know?

**Comment by tbrodahl** [comment]
Should be 31, but on the start button its 30 for some reason
