### ISSUE TITLE
SAFARI - NAV opens, but links are not clickable

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#47]

**Comment by andrewmartin** [comment]
![](http://cloud.believelabs.com/250E2q430L0Z/Screen%20Recording%202016-11-19%20at%2015.47.gif)

**Comment by andrewmartin** [comment]
http://cloud.believelabs.com/250E2q430L0Z/Screen%20Recording%202016-11-19%20at%2015.47.gif (for some reason it wasn't displaying on Github?)
