### ISSUE TITLE
Make HEADER BGs same color as the IMAGE above it, so when it loads, its not so jarring with the WHITE on some of them.

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#48]
HOMEPAGE TOP #D7E1E3

ABOUT TOP  #5D737A

DS #55666D

ST #746E5E

CONTACT #5E676E

PROSTATE CANCER FACTS #4C5246

**Comment by andrewmartin** [comment]
I'm a little confused about this one. What header bg's? Can you offer up a screenshot just so I'm sure to make this the correct way?

**Comment by tbrodahl** [comment]
just the color behind the image as it loads... it won't be  visible once the image loads

**Comment by tbrodahl** [comment]
![screen shot 2016-11-19 at 4 07 36 pm](https://cloud.githubusercontent.com/assets/5798011/20459341/55487656-ae72-11e6-94e1-00ef9053e832.png)

**Comment by tbrodahl** [comment]
if it was that blue color, then we could still read the txt while the image loads. Lets us get away with having the big images.

**Comment by andrewmartin** [comment]
Got it. I figured, the reason I was confused is because of the semantics; I've been calling that area the `intro` section, the `header` is where the menu is. Thanks for clarifying.
