### ISSUE TITLE
PROSTATE CANCER FACTS - need to replace image

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#51]
His head is cut off. I'm exporting a new version now.

**Comment by tbrodahl** [comment]
Actually the image is fine, can we just have it expand from the top instead of middle as it is now? or should i crop it and export a shorter version?

**Comment by andrewmartin** [comment]
You need to re-crop it, if you can; basically just include the approximate amount of space shown in the "yellow" area here:

![image](https://cloud.githubusercontent.com/assets/273842/20586817/a5465298-b1bc-11e6-854d-f5051e7cd3df.png)

**Comment by tbrodahl** [comment]
![ustoo](https://cloud.githubusercontent.com/assets/5798011/20587629/07a7f7f0-b1c4-11e6-9a41-bf70551e4146.jpg)

basically this... just make the line "Online..." not BOLD

**Comment by andrewmartin** [comment]
happy thanksgiving. Did you upload another image?

**Comment by tbrodahl** [comment]
Just added it to the folder. PCF2-Background.jpg

**Comment by tbrodahl** [comment]
Let me know if that solves it. Thx.

**Comment by andrewmartin** [comment]
![image](https://cloud.githubusercontent.com/assets/273842/20698217/4947dbfa-b5b4-11e6-80f3-0be06986937d.png)

Looks better to me?
