### ISSUE TITLE
TrueNTH LOGO issue in the footer seems to only happen on my non-retina display

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#53]
Anything we can do about that?

**Comment by andrewmartin** [comment]
This one is hard, because I can't really re-create (so I can't quickly or easily try fixes). 

Question. Do the arrows disappear as well? The icons in the side nav?

**Comment by tbrodahl** [comment]
Just the TrueNTH logo seems to be doing this. I wonder if its soemthing with that SVG? Maybe we just use a PNG?

**Comment by andrewmartin** [comment]
my thoughts exactly. i'm out for the night but will just use PNG instead.

**Comment by andrewmartin** [comment]
swapped both of these logos for PNG's
