### ISSUE TITLE
iPAD issues - Not displaying images and breaking stacking? 

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#54]
Just checked it on my old iPad. Have a look at these screens.
![img_0103](https://cloud.githubusercontent.com/assets/5798011/20544446/01069d08-b0bf-11e6-99b3-ec8999e16364.PNG)
![img_0104](https://cloud.githubusercontent.com/assets/5798011/20544447/0108187c-b0bf-11e6-8195-44bbc2308437.PNG)
![img_0106](https://cloud.githubusercontent.com/assets/5798011/20544448/010888f2-b0bf-11e6-9de1-087b20809c9b.PNG)
![img_0107](https://cloud.githubusercontent.com/assets/5798011/20544445/0103f918-b0bf-11e6-9895-2058f2444412.PNG)

**Comment by andrewmartin** [comment]
What’s the issue (sorry if obvious) with the last two screenshots?

**Comment by tbrodahl** [comment]
SVG's not showing up. 

TRUENTH LOGO and MOVEMBER LOGO in the FOOTER. 

TOOL ICONS in the SIDE NAV.

**Comment by andrewmartin** [comment]
Doh. This is the problem looking at things on my iPhone. Got it.

**Comment by andrewmartin** [comment]
I'm really confused, because I'm not seeing it like that at all on my iPad. Might be hard to debug this...Let's sync up when we're both online to try and fix these (these are hard, again, because I can't re-create so it's hard to know if a "fix" worked).
