### ISSUE TITLE
JOIN US - MOBILE Center Box Vertically on the page

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#55]
![image](https://cloud.githubusercontent.com/assets/5798011/20544493/40091f4e-b0bf-11e6-9df4-1d15788e9dc6.png)

**Comment by andrewmartin** [comment]
So, this is actually something I intended to do (have it on top). 

Reason being, we can't have a safe way to calculate or set expectations for the height of all mobile browsers. This is pretty standard practice from what I've seen, and it also helps the user experience; for example, they don't have to scroll at all to log in, which makes for a better experience.

**Comment by andrewmartin** [comment]
PS I also fixed that text break a bit...
