### ISSUE TITLE
REMOVE non-active DOWN ARROWS

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#58]
Leave top   ▿ icon (the clickable one)

-----

Remove down carrots in sections below/towards bottom where they are static. 
(ex: above the call to action box of DS and ST)

**Comment by andrewmartin** [comment]
Sorry, this one is confusing me a bit...but I think I got it done? Can you let me know specifically (w/ screenshots) if I missed any or took out the wrong ones?

**Comment by tbrodahl** [comment]
![image](https://cloud.githubusercontent.com/assets/5798011/20587696/7dcf863c-b1c4-11e6-9ed3-e3dad59d5081.png)

![image](https://cloud.githubusercontent.com/assets/5798011/20587698/85c42e06-b1c4-11e6-9465-faaeee9e462e.png)

These guys on the homepage too.
