### ISSUE TITLE
PCFACTS - Copy edit in the ADDITIONAL RESOURCES section

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#60]
![image](https://cloud.githubusercontent.com/assets/5798011/20544865/f7c90df0-b0c0-11e6-8ce6-7f0f757920cb.png)

Add UsTOO
and make "Online Prostate Cancer Discussion Forum and Community" (not bold)

**Comment by andrewmartin** [comment]
Hmm, I'm confused about this, can you clarify? I removed the boldness of the text, but not sure what you mean. Sorry, I keep re-reading the screenshot above and I can't get it without the context.

**Comment by tbrodahl** [comment]
Basically it should look like this: 

![ustoo](https://cloud.githubusercontent.com/assets/5798011/20587729/ac58fe84-b1c4-11e6-91c3-7d1f86af3521.jpg)

**Comment by tbrodahl** [comment]
But the "Online Prostate Cancer...." line should not be bold..

**Comment by andrewmartin** [comment]
👍🏻 ok no prob
