### ISSUE TITLE
ADD VIDEOS

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#62]
We only have two so far. 

Here are embeds for the videos:

**HOMEPAGE / DS PAGE code :** 
<div style="position:relative;height:0;padding-bottom:56.25%"><iframe class='sproutvideo-player' src='//videos.sproutvideo.com/embed/e89bd1bd181ae4cf60/1e7fa0493e528f7c?type=hd&amp;playerColor=2f3437' style='position:absolute;width:100%;height:100%;left:0;top:0' frameborder='0' allowfullscreen></iframe></div>

**ABOUT / ST PAGE code:**
<div style="position:relative;height:0;padding-bottom:56.25%"><iframe class='sproutvideo-player' src='//videos.sproutvideo.com/embed/a49bd1bd181ae3c72c/b947ee462a45662e?type=hd' style='position:absolute;width:100%;height:100%;left:0;top:0' frameborder='0' allowfullscreen></iframe></div>

**Comment by andrewmartin** [comment]
Okay, got these in...

I'm assuming we want an autoplay option? I added it (figuring as soon as you hit "Watch," you want the video to start playing).

**Comment by tbrodahl** [comment]
Looks great!!
