### ISSUE TITLE
add favicon zip

### ISSUE THREAD

**Issue by andrewmartin** [tbrodahl/truenth#64]
Hey man, we need a favicon for this site.

I'd recommend using something like this:
http://iconogen.com/upload.php

Just send me the zip file it outputs, I'll take it from there.

**Comment by tbrodahl** [comment]
[your_new_images.zip](https://github.com/tbrodahl/truenth/files/618003/your_new_images.zip)

try this?

**Comment by andrewmartin** [comment]
yep, perfect
