### ISSUE TITLE
HOMEPAGE - SYMPTOM TRACKER tool boxes are the wrong color, should be brown at 80%

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#8]

**Comment by tbrodahl** [comment]
![st-color](https://cloud.githubusercontent.com/assets/5798011/20071568/d207d10c-a4d9-11e6-9b81-b3deddd7bb55.jpg)

**Comment by andrewmartin** [comment]
I noticed a lot of variations in the colors here; there were different hues throughout. I'm wondering how we can get on the same page here or set up some sort of a standard for colors, because I pulled all the colors you're seeing directly from the Sketch file.
