### ISSUE TITLE
HOMEPAGE - TrueNTH Logo on the white bar looks blurry - I can export a separate version for that size if you want

### ISSUE THREAD

**Issue by tbrodahl** [tbrodahl/truenth#9]

**Comment by tbrodahl** [comment]
![logoonwhite](https://cloud.githubusercontent.com/assets/5798011/20071577/d780e7a4-a4d9-11e6-847b-da99df7f8914.jpg)

**Comment by andrewmartin** [comment]
Yeah, let's try and get an SVG for this. If there is any chance you could put one in the `symlink` that would be excellent.

**Comment by andrewmartin** [comment]
Please give me a new version; I exported directly from Sketch. Let me know when in Dropbox, maybe rename it to `logo-v2.png` or something so I am sure it's the new.
